apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger-system
resources:
  - namespace.yaml
  - gcp-kubeconfig.yaml
  - kuma-request-success-rate.yaml
  - kuma-request-duration.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml